import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { build } from 'esbuild';

const file = '明文源吗';
const { version } = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
const { outputFiles } = await build({
  entryPoints: ['src/worker.js'], bundle: true, write: false,
  format: 'esm', target: 'es2022', charset: 'utf8',
  external: ['cloudflare:sockets'], legalComments: 'none',
  loader: { '.css': 'text' },
  plugins: [{ name: 'inline-browser-scripts', setup(builder) {
    builder.onLoad({ filter: /\.client\.js$/ }, async ({ path }) => ({
      contents: await readFile(path, 'utf8'), loader: 'text'
    }));
  } }],
  banner: { js: `// CFnew v${version} — generated by npm run build; edit src/ instead.` }
});
const code = outputFiles[0].text;
if (process.argv.includes('--check')) {
  assert.equal(await readFile(file, 'utf8'), code, `${file} is out of date; run npm run build`);
} else {
  await writeFile(file, code);
}
